name: Tool - Convert2HDF5 - Yearly

on:
  # schedule:
  #   - cron: '0 0 1 1 *'
  workflow_dispatch:       # Permite execução manual do workflow


env:
  TAG: 24.10
  REPOSITORY: mohid-water-modelling-system
  DOCKER_IMAGE_NAME: tools/convert2hdf5
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Read Image NAME
        run: echo "The Docker image name is $IMAGE_NAME"
      
      - name: Use Docker image name
        run: echo "The Docker image name is $DOCKER_IMAGE_NAME"
      
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3 # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Solutions/dockers/Convert2HDF5/dockerfile --tag ghcr.io/${{ env.REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }}

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ env.REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }}